type nonrec validation_exception_reason =
  | KMS_INVALID_ARN [@ocaml.doc ""]
  | KMS_INVALID_KEY_USAGE [@ocaml.doc ""]
  | KMS_INVALID_STATE [@ocaml.doc ""]
  | KMS_DISABLED [@ocaml.doc ""]
[@@ocaml.doc ""]

type nonrec request_id = string [@@ocaml.doc ""]

type nonrec exception_message = string [@@ocaml.doc ""]

type nonrec validation_exception = {
  message : exception_message option; [@ocaml.doc ""]
  request_id : request_id option;
      [@ocaml.doc
        "The identifier for each request. This value is a globally unique ID that is generated by \
         the identity store service for each sent request, and is then returned inside the \
         exception if the request fails.\n"]
  reason : validation_exception_reason option;
      [@ocaml.doc
        "Indicates the reason for the validation error when the service is unable to access a \
         Customer Managed KMS key. For non-KMS permission errors, this field is not included.\n"]
}
[@@ocaml.doc "The request failed because it contains a syntax error.\n"]

type nonrec resource_not_found_exception_reason = KMS_KEY_NOT_FOUND [@ocaml.doc ""]
[@@ocaml.doc ""]

type nonrec resource_id = string [@@ocaml.doc ""]

type nonrec resource_type =
  | GROUP [@ocaml.doc ""]
  | USER [@ocaml.doc ""]
  | IDENTITY_STORE [@ocaml.doc ""]
  | GROUP_MEMBERSHIP [@ocaml.doc ""]
  | RESOURCE_POLICY [@ocaml.doc ""]
[@@ocaml.doc ""]

type nonrec resource_not_found_exception = {
  resource_type : resource_type option;
      [@ocaml.doc
        "An enum object indicating the type of resource in the identity store service. Valid \
         values include USER, GROUP, and IDENTITY_STORE.\n"]
  resource_id : resource_id option;
      [@ocaml.doc
        "The identifier for a resource in the identity store that can be used as [UserId] or \
         [GroupId]. The format for [ResourceId] is either [UUID] or [1234567890-UUID], where \
         [UUID] is a randomly generated value for each resource when it is created and \
         [1234567890] represents the [ IdentityStoreId] string value. In the case that the \
         identity store is migrated from a legacy SSO identity store, the [ResourceId] for that \
         identity store will be in the format of [UUID]. Otherwise, it will be in the \
         [1234567890-UUID] format.\n"]
  reason : resource_not_found_exception_reason option;
      [@ocaml.doc
        "Indicates the reason for a resource not found error when the service is unable to access \
         a Customer Managed KMS key. For non-KMS permission errors, this field is not included.\n"]
  message : exception_message option; [@ocaml.doc ""]
  request_id : request_id option;
      [@ocaml.doc
        "The identifier for each request. This value is a globally unique ID that is generated by \
         the identity store service for each sent request, and is then returned inside the \
         exception if the request fails.\n"]
}
[@@ocaml.doc "Indicates that a requested resource is not found.\n"]

type nonrec next_token = string [@@ocaml.doc ""]

type nonrec string_type = string [@@ocaml.doc ""]

type nonrec date_type = Smaws_Lib.CoreTypes.Timestamp.t [@@ocaml.doc ""]

type nonrec member_id =
  | UserId of resource_id
      [@ocaml.doc "An object containing the identifiers of resources that can be members.\n"]
[@@ocaml.doc "An object containing the identifier of a group member.\n"]

type nonrec identity_store_id = string [@@ocaml.doc ""]

type nonrec group_membership = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  membership_id : resource_id option;
      [@ocaml.doc "The identifier for a [GroupMembership] object in an identity store.\n"]
  group_id : resource_id option; [@ocaml.doc "The identifier for a group in the identity store.\n"]
  member_id : member_id option;
      [@ocaml.doc
        "An object that contains the identifier of a group member. Setting the [UserID] field to \
         the specific identifier for a user indicates that the user is a member of the group.\n"]
  created_at : date_type option;
      [@ocaml.doc "The date and time the group membership was created.\n"]
  updated_at : date_type option;
      [@ocaml.doc "The date and time the group membership was last updated.\n"]
  created_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that created the group membership.\n"]
  updated_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that last updated the group membership.\n"]
}
[@@ocaml.doc
  "Contains the identifiers for a group, a group member, and a [GroupMembership] object in the \
   identity store.\n"]

type nonrec group_memberships = group_membership list [@@ocaml.doc ""]

type nonrec list_group_memberships_for_member_response = {
  group_memberships : group_memberships;
      [@ocaml.doc "A list of [GroupMembership] objects in the group for a specified member.\n"]
  next_token : next_token option;
      [@ocaml.doc
        "The pagination token used for the [ListUsers], [ListGroups], and [ ListGroupMemberships] \
         API operations. This value is generated by the identity store service. It is returned in \
         the API response if the total results are more than the size of one page. This token is \
         also returned when it is used in the API request to search for the next page. \n"]
}
[@@ocaml.doc ""]

type nonrec max_results = int [@@ocaml.doc ""]

type nonrec list_group_memberships_for_member_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  member_id : member_id;
      [@ocaml.doc
        "An object that contains the identifier of a group member. Setting the [UserID] field to \
         the specific identifier for a user indicates that the user is a member of the group.\n"]
  max_results : max_results option;
      [@ocaml.doc
        "The maximum number of results to be returned per request. This parameter is used in the [ \
         ListUsers] and [ListGroups] requests to specify how many results to return in one page. \
         The length limit is 50 characters.\n"]
  next_token : next_token option;
      [@ocaml.doc
        "The pagination token used for the [ListUsers], [ListGroups], and [ ListGroupMemberships] \
         API operations. This value is generated by the identity store service. It is returned in \
         the API response if the total results are more than the size of one page. This token is \
         also returned when it is used in the API request to search for the next page.\n"]
}
[@@ocaml.doc ""]

type nonrec boolean_type = bool [@@ocaml.doc ""]

type nonrec group_membership_existence_result = {
  group_id : resource_id option; [@ocaml.doc "The identifier for a group in the identity store.\n"]
  member_id : member_id option;
      [@ocaml.doc
        "An object that contains the identifier of a group member. Setting the [UserID] field to \
         the specific identifier for a user indicates that the user is a member of the group.\n"]
  membership_exists : boolean_type option;
      [@ocaml.doc "Indicates whether a membership relation exists or not.\n"]
}
[@@ocaml.doc "Indicates whether a resource is a member of a group in the identity store.\n"]

type nonrec group_membership_existence_results = group_membership_existence_result list
[@@ocaml.doc ""]

type nonrec is_member_in_groups_response = {
  results : group_membership_existence_results;
      [@ocaml.doc "A list containing the results of membership existence checks.\n"]
}
[@@ocaml.doc ""]

type nonrec group_ids = resource_id list [@@ocaml.doc ""]

type nonrec is_member_in_groups_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  member_id : member_id; [@ocaml.doc "An object containing the identifier of a group member.\n"]
  group_ids : group_ids; [@ocaml.doc "A list of identifiers for groups in the identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec get_user_id_response = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  user_id : resource_id; [@ocaml.doc "The identifier for a user in the identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec attribute_value = Smaws_Lib.CoreTypes.Document.t [@@ocaml.doc ""]

type nonrec attribute_path = string [@@ocaml.doc ""]

type nonrec unique_attribute = {
  attribute_path : attribute_path;
      [@ocaml.doc
        "A string representation of the path to a given attribute or sub-attribute. Supports \
         JMESPath.\n"]
  attribute_value : attribute_value;
      [@ocaml.doc
        "The value of the attribute. This is a [Document] type. This type is not supported by Java \
         V1, Go V1, and older versions of the CLI.\n"]
}
[@@ocaml.doc "An entity attribute that's unique to a specific entity.\n"]

type nonrec external_id_identifier = string [@@ocaml.doc ""]

type nonrec external_id_issuer = string [@@ocaml.doc ""]

type nonrec external_id = {
  issuer : external_id_issuer; [@ocaml.doc "The issuer for an external identifier.\n"]
  id : external_id_identifier;
      [@ocaml.doc "The identifier issued to this resource by an external identity provider.\n"]
}
[@@ocaml.doc "The identifier issued to this resource by an external identity provider.\n"]

type nonrec alternate_identifier =
  | ExternalId of external_id
      [@ocaml.doc "The identifier issued to this resource by an external identity provider.\n"]
  | UniqueAttribute of unique_attribute
      [@ocaml.doc "An entity attribute that's unique to a specific entity.\n"]
[@@ocaml.doc
  "A unique identifier for a user or group that is not the primary identifier. This value can be \
   an identifier from an external identity provider (IdP) that is associated with the user, the \
   group, or a unique attribute.\n"]

type nonrec get_user_id_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  alternate_identifier : alternate_identifier;
      [@ocaml.doc
        "A unique identifier for a user or group that is not the primary identifier. This value \
         can be an identifier from an external identity provider (IdP) that is associated with the \
         user, the group, or a unique attribute. For the unique attribute, the only valid paths \
         are [ userName] and [emails.value].\n"]
}
[@@ocaml.doc ""]

type nonrec get_group_membership_id_response = {
  membership_id : resource_id;
      [@ocaml.doc "The identifier for a [GroupMembership] in an identity store.\n"]
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec get_group_membership_id_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  group_id : resource_id; [@ocaml.doc "The identifier for a group in the identity store.\n"]
  member_id : member_id;
      [@ocaml.doc
        "An object that contains the identifier of a group member. Setting the [UserID] field to \
         the specific identifier for a user indicates that the user is a member of the group.\n"]
}
[@@ocaml.doc ""]

type nonrec get_group_id_response = {
  group_id : resource_id; [@ocaml.doc "The identifier for a group in the identity store.\n"]
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec get_group_id_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  alternate_identifier : alternate_identifier;
      [@ocaml.doc
        "A unique identifier for a user or group that is not the primary identifier. This value \
         can be an identifier from an external identity provider (IdP) that is associated with the \
         user, the group, or a unique attribute. For the unique attribute, the only valid path is \
         [ displayName].\n"]
}
[@@ocaml.doc ""]

type nonrec access_denied_exception_reason = KMS_ACCESS_DENIED [@ocaml.doc ""] [@@ocaml.doc ""]

type nonrec access_denied_exception = {
  message : exception_message option; [@ocaml.doc ""]
  request_id : request_id option;
      [@ocaml.doc
        "The identifier for each request. This value is a globally unique ID that is generated by \
         the identity store service for each sent request, and is then returned inside the \
         exception if the request fails.\n"]
  reason : access_denied_exception_reason option;
      [@ocaml.doc
        "Indicates the reason for an access denial when returned by KMS while accessing a Customer \
         Managed KMS key. For non-KMS access-denied errors, this field is not included.\n"]
}
[@@ocaml.doc "You do not have sufficient access to perform this action.\n"]

type nonrec sensitive_string_type = string [@@ocaml.doc ""]

type nonrec address = {
  street_address : sensitive_string_type option; [@ocaml.doc "The street of the address.\n"]
  locality : sensitive_string_type option; [@ocaml.doc "A string of the address locality.\n"]
  region : sensitive_string_type option; [@ocaml.doc "The region of the address.\n"]
  postal_code : sensitive_string_type option; [@ocaml.doc "The postal code of the address.\n"]
  country : sensitive_string_type option; [@ocaml.doc "The country of the address.\n"]
  formatted : sensitive_string_type option;
      [@ocaml.doc "A string containing a formatted version of the address for display.\n"]
  type_ : sensitive_string_type option;
      [@ocaml.doc "A string representing the type of address. For example, \"Home.\"\n"]
  primary : boolean_type option;
      [@ocaml.doc
        "A Boolean value representing whether this is the primary address for the associated \
         resource.\n"]
}
[@@ocaml.doc "The address associated with the specified user.\n"]

type nonrec addresses = address list [@@ocaml.doc ""]

type nonrec attribute_operation = {
  attribute_path : attribute_path;
      [@ocaml.doc
        "A string representation of the path to a given attribute or sub-attribute. Supports \
         JMESPath.\n"]
  attribute_value : attribute_value option;
      [@ocaml.doc
        "The value of the attribute. This is a [Document] type. This type is not supported by Java \
         V1, Go V1, and older versions of the CLI.\n"]
}
[@@ocaml.doc
  "An operation that applies to the requested group. This operation might add, replace, or remove \
   an attribute.\n"]

type nonrec attribute_operations = attribute_operation list [@@ocaml.doc ""]

type nonrec conflict_exception_reason =
  | UNIQUENESS_CONSTRAINT_VIOLATION [@ocaml.doc ""]
  | CONCURRENT_MODIFICATION [@ocaml.doc ""]
[@@ocaml.doc ""]

type nonrec conflict_exception = {
  message : exception_message option; [@ocaml.doc ""]
  request_id : request_id option;
      [@ocaml.doc
        "The identifier for each request. This value is a globally unique ID that is generated by \
         the identity store service for each sent request, and is then returned inside the \
         exception if the request fails.\n"]
  reason : conflict_exception_reason option;
      [@ocaml.doc
        "Indicates the reason for a conflict error when the service is unable to access a Customer \
         Managed KMS key. For non-KMS permission errors, this field is not included.\n"]
}
[@@ocaml.doc
  "This request cannot be completed for one of the following reasons:\n\n\
  \ {ul\n\
  \       {-  Performing the requested operation would violate an existing uniqueness claim in the \
   identity store. Resolve the conflict before retrying this request.\n\
  \           \n\
  \            }\n\
  \       {-  The requested resource was being concurrently modified by another request.\n\
  \           \n\
  \            }\n\
  \       }\n\
  \  "]

type nonrec service_quota_exceeded_exception = {
  message : exception_message option; [@ocaml.doc ""]
  request_id : request_id option;
      [@ocaml.doc
        "The identifier for each request. This value is a globally unique ID that is generated by \
         the identity store service for each sent request, and is then returned inside the \
         exception if the request fails.\n"]
}
[@@ocaml.doc
  "The request would cause the number of users or groups in the identity store to exceed the \
   maximum allowed.\n"]

type nonrec create_group_response = {
  group_id : resource_id;
      [@ocaml.doc "The identifier of the newly created group in the identity store.\n"]
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec group_display_name = string [@@ocaml.doc ""]

type nonrec create_group_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  display_name : group_display_name option;
      [@ocaml.doc
        "A string containing the name of the group. This value is commonly displayed when the \
         group is referenced. [Administrator] and [AWSAdministrators] are reserved names and can't \
         be used for users or groups.\n"]
  description : sensitive_string_type option;
      [@ocaml.doc "A string containing the description of the group.\n"]
}
[@@ocaml.doc ""]

type nonrec create_group_membership_response = {
  membership_id : resource_id;
      [@ocaml.doc "The identifier for a newly created [GroupMembership] in an identity store.\n"]
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec create_group_membership_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  group_id : resource_id; [@ocaml.doc "The identifier for a group in the identity store.\n"]
  member_id : member_id;
      [@ocaml.doc
        "An object that contains the identifier of a group member. Setting the [UserID] field to \
         the specific identifier for a user indicates that the user is a member of the group.\n"]
}
[@@ocaml.doc ""]

type nonrec create_user_response = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  user_id : resource_id;
      [@ocaml.doc "The identifier of the newly created user in the identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec extension_name = string [@@ocaml.doc ""]

type nonrec extensions = (extension_name * attribute_value) list [@@ocaml.doc ""]

type nonrec role = {
  value : sensitive_string_type option;
      [@ocaml.doc "A string containing a role name. For example, \"Researcher.\"\n"]
  type_ : sensitive_string_type option;
      [@ocaml.doc "A string representing the type of role. For example, \"Work.\"\n"]
  primary : boolean_type option;
      [@ocaml.doc
        "A Boolean value representing whether this is the primary role for the associated resource.\n"]
}
[@@ocaml.doc "The role associated with the user.\n"]

type nonrec roles = role list [@@ocaml.doc ""]

type nonrec photo = {
  value : sensitive_string_type;
      [@ocaml.doc
        "The photo data or URL. Supported formats include jpg, jpeg, png, and gif. This field is \
         required for all photo entries.\n"]
  type_ : sensitive_string_type option;
      [@ocaml.doc
        "The type of photo. This field is optional and can be used to categorize different types \
         of photos.\n"]
  display : sensitive_string_type option;
      [@ocaml.doc
        "A human-readable description of the photo for display purposes. This optional field \
         provides context about the photo.\n"]
  primary : boolean_type option;
      [@ocaml.doc
        "Specifies whether this is the user's primary photo. Default value is [false]. Only one \
         photo can be designated as primary per user.\n"]
}
[@@ocaml.doc
  "Contains information about a user's photo. Users can have up to 3 photos, with one designated \
   as primary. Supports common image formats, including jpg, jpeg, png, and gif.\n"]

type nonrec photos = photo list [@@ocaml.doc ""]

type nonrec phone_number = {
  value : sensitive_string_type option;
      [@ocaml.doc
        "A string containing a phone number. For example, \"8675309\" or \"+1 (800) 123-4567\". \n"]
  type_ : sensitive_string_type option;
      [@ocaml.doc "A string representing the type of a phone number. For example, \"Mobile.\"\n"]
  primary : boolean_type option;
      [@ocaml.doc
        "A Boolean value representing whether this is the primary phone number for the associated \
         resource.\n"]
}
[@@ocaml.doc "The phone number associated with the user.\n"]

type nonrec phone_numbers = phone_number list [@@ocaml.doc ""]

type nonrec email = {
  value : sensitive_string_type option;
      [@ocaml.doc "A string containing an email address. For example, \"johndoe\\@amazon.com.\"\n"]
  type_ : sensitive_string_type option;
      [@ocaml.doc "A string representing the type of address. For example, \"Work.\"\n"]
  primary : boolean_type option;
      [@ocaml.doc
        "A Boolean value representing whether this is the primary email address for the associated \
         resource.\n"]
}
[@@ocaml.doc "The email address associated with the user.\n"]

type nonrec emails = email list [@@ocaml.doc ""]

type nonrec name = {
  formatted : sensitive_string_type option;
      [@ocaml.doc "A string containing a formatted version of the name for display.\n"]
  family_name : sensitive_string_type option; [@ocaml.doc "The family name of the user.\n"]
  given_name : sensitive_string_type option; [@ocaml.doc "The given name of the user.\n"]
  middle_name : sensitive_string_type option; [@ocaml.doc "The middle name of the user.\n"]
  honorific_prefix : sensitive_string_type option;
      [@ocaml.doc "The honorific prefix of the user. For example, \"Dr.\"\n"]
  honorific_suffix : sensitive_string_type option;
      [@ocaml.doc "The honorific suffix of the user. For example, \"M.D.\"\n"]
}
[@@ocaml.doc "The full name of the user.\n"]

type nonrec user_name = string [@@ocaml.doc ""]

type nonrec create_user_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  user_name : user_name option;
      [@ocaml.doc
        "A unique string used to identify the user. The length limit is 128 characters. This value \
         can consist of letters, accented characters, symbols, numbers, and punctuation. This \
         value is specified at the time the user is created and stored as an attribute of the user \
         object in the identity store. [Administrator] and [AWSAdministrators] are reserved names \
         and can't be used for users or groups.\n"]
  name : name option;
      [@ocaml.doc
        "An object containing the name of the user. When used in IAM Identity Center, this \
         parameter is required.\n"]
  display_name : sensitive_string_type option;
      [@ocaml.doc
        "A string containing the name of the user. This value is typically formatted for display \
         when the user is referenced. For example, \"John Doe.\" When used in IAM Identity Center, \
         this parameter is required.\n"]
  nick_name : sensitive_string_type option;
      [@ocaml.doc "A string containing an alternate name for the user.\n"]
  profile_url : sensitive_string_type option;
      [@ocaml.doc "A string containing a URL that might be associated with the user.\n"]
  emails : emails option;
      [@ocaml.doc
        "A list of [Email] objects containing email addresses associated with the user.\n"]
  addresses : addresses option;
      [@ocaml.doc "A list of [Address] objects containing addresses associated with the user.\n"]
  phone_numbers : phone_numbers option;
      [@ocaml.doc
        "A list of [PhoneNumber] objects containing phone numbers associated with the user.\n"]
  user_type : sensitive_string_type option;
      [@ocaml.doc
        "A string indicating the type of user. Possible values are left unspecified. The value can \
         vary based on your specific use case.\n"]
  title : sensitive_string_type option;
      [@ocaml.doc
        "A string containing the title of the user. Possible values are left unspecified. The \
         value can vary based on your specific use case.\n"]
  preferred_language : sensitive_string_type option;
      [@ocaml.doc
        "A string containing the preferred language of the user. For example, \"American English\" \
         or \"en-us.\"\n"]
  locale : sensitive_string_type option;
      [@ocaml.doc "A string containing the geographical region or location of the user.\n"]
  timezone : sensitive_string_type option;
      [@ocaml.doc "A string containing the time zone of the user.\n"]
  photos : photos option;
      [@ocaml.doc
        "A list of photos associated with the user. You can add up to 3 photos per user. Each \
         photo can include a value, type, display name, and primary designation.\n"]
  website : sensitive_string_type option;
      [@ocaml.doc
        "The user's personal website or blog URL. This field allows users to provide a link to \
         their personal or professional website.\n"]
  birthdate : sensitive_string_type option;
      [@ocaml.doc
        "The user's birthdate in YYYY-MM-DD format. This field supports standard date format for \
         storing personal information.\n"]
  roles : roles option;
      [@ocaml.doc "A list of [Role] objects containing roles associated with the user.\n"]
  extensions : extensions option;
      [@ocaml.doc
        "A map with additional attribute extensions for the user. Each map key corresponds to an \
         extension name, while map values represent extension data in [Document] type (not \
         supported by Java V1, Go V1 and older versions of the CLI). \
         [aws:identitystore:enterprise] is the only supported extension name.\n"]
}
[@@ocaml.doc ""]

type nonrec delete_group_response = unit [@@ocaml.doc ""]

type nonrec delete_group_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  group_id : resource_id; [@ocaml.doc "The identifier for a group in the identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec delete_group_membership_response = unit [@@ocaml.doc ""]

type nonrec delete_group_membership_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  membership_id : resource_id;
      [@ocaml.doc "The identifier for a [GroupMembership] in an identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec delete_user_response = unit [@@ocaml.doc ""]

type nonrec delete_user_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  user_id : resource_id; [@ocaml.doc "The identifier for a user in the identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec external_ids = external_id list [@@ocaml.doc ""]

type nonrec describe_group_response = {
  group_id : resource_id; [@ocaml.doc "The identifier for a group in the identity store.\n"]
  display_name : group_display_name option;
      [@ocaml.doc
        "The group\226\128\153s display name value. The length limit is 1,024 characters. This \
         value can consist of letters, accented characters, symbols, numbers, punctuation, tab, \
         new line, carriage return, space, and nonbreaking space in this attribute. This value is \
         specified at the time that the group is created and stored as an attribute of the group \
         object in the identity store.\n"]
  external_ids : external_ids option;
      [@ocaml.doc
        "A list of [ExternalId] objects that contains the identifiers issued to this resource by \
         an external identity provider.\n"]
  description : sensitive_string_type option;
      [@ocaml.doc "A string containing a description of the group.\n"]
  created_at : date_type option; [@ocaml.doc "The date and time the group was created.\n"]
  updated_at : date_type option; [@ocaml.doc "The date and time the group was last updated.\n"]
  created_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that created the group.\n"]
  updated_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that last updated the group.\n"]
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec describe_group_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc
        "The globally unique identifier for the identity store, such as [d-1234567890]. In this \
         example, [d-] is a fixed prefix, and [1234567890] is a randomly generated string that \
         contains numbers and lower case letters. This value is generated at the time that a new \
         identity store is created.\n"]
  group_id : resource_id; [@ocaml.doc "The identifier for a group in the identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec describe_group_membership_response = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  membership_id : resource_id;
      [@ocaml.doc "The identifier for a [GroupMembership] in an identity store.\n"]
  group_id : resource_id; [@ocaml.doc "The identifier for a group in the identity store.\n"]
  member_id : member_id; [@ocaml.doc ""]
  created_at : date_type option;
      [@ocaml.doc "The date and time the group membership was created.\n"]
  updated_at : date_type option;
      [@ocaml.doc "The date and time the group membership was last updated.\n"]
  created_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that created the group membership.\n"]
  updated_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that last updated the group membership.\n"]
}
[@@ocaml.doc ""]

type nonrec describe_group_membership_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  membership_id : resource_id;
      [@ocaml.doc "The identifier for a [GroupMembership] in an identity store.\n"]
}
[@@ocaml.doc ""]

type nonrec user_status = ENABLED [@ocaml.doc ""] | DISABLED [@ocaml.doc ""] [@@ocaml.doc ""]

type nonrec describe_user_response = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  user_id : resource_id; [@ocaml.doc "The identifier for a user in the identity store.\n"]
  user_name : user_name option;
      [@ocaml.doc
        "A unique string used to identify the user. The length limit is 128 characters. This value \
         can consist of letters, accented characters, symbols, numbers, and punctuation. This \
         value is specified at the time the user is created and stored as an attribute of the user \
         object in the identity store.\n"]
  external_ids : external_ids option;
      [@ocaml.doc
        "A list of [ExternalId] objects that contains the identifiers issued to this resource by \
         an external identity provider.\n"]
  name : name option; [@ocaml.doc "The name of the user.\n"]
  display_name : sensitive_string_type option; [@ocaml.doc "The display name of the user.\n"]
  nick_name : sensitive_string_type option;
      [@ocaml.doc "An alternative descriptive name for the user.\n"]
  profile_url : sensitive_string_type option; [@ocaml.doc "A URL link for the user's profile.\n"]
  emails : emails option; [@ocaml.doc "The email address of the user.\n"]
  addresses : addresses option; [@ocaml.doc "The physical address of the user.\n"]
  phone_numbers : phone_numbers option;
      [@ocaml.doc "A list of [PhoneNumber] objects associated with a user.\n"]
  user_type : sensitive_string_type option; [@ocaml.doc "A string indicating the type of user.\n"]
  title : sensitive_string_type option; [@ocaml.doc "A string containing the title of the user.\n"]
  preferred_language : sensitive_string_type option;
      [@ocaml.doc "The preferred language of the user.\n"]
  locale : sensitive_string_type option;
      [@ocaml.doc "A string containing the geographical region or location of the user.\n"]
  timezone : sensitive_string_type option; [@ocaml.doc "The time zone for a user.\n"]
  user_status : user_status option; [@ocaml.doc "The current status of the user account.\n"]
  photos : photos option;
      [@ocaml.doc
        "A list of photos associated with the user. Returns up to 3 photos with their associated \
         metadata including type, display name, and primary designation.\n"]
  website : sensitive_string_type option;
      [@ocaml.doc
        "The user's personal website or blog URL. Returns the stored website information for the \
         user.\n"]
  birthdate : sensitive_string_type option;
      [@ocaml.doc
        "The user's birthdate in YYYY-MM-DD format. This field returns the stored birthdate \
         information for the user.\n"]
  roles : roles option; [@ocaml.doc "The roles of the user.\n"]
  created_at : date_type option; [@ocaml.doc "The date and time the user was created.\n"]
  created_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that created the user.\n"]
  updated_at : date_type option; [@ocaml.doc "The date and time the user was last updated.\n"]
  updated_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that last updated the user.\n"]
  extensions : extensions option;
      [@ocaml.doc
        "A map of explicitly requested attribute extensions associated with the user. Not \
         populated if the user has no requested extensions.\n"]
}
[@@ocaml.doc ""]

type nonrec extension_names = extension_name list [@@ocaml.doc ""]

type nonrec describe_user_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc
        "The globally unique identifier for the identity store, such as [d-1234567890]. In this \
         example, [d-] is a fixed prefix, and [1234567890] is a randomly generated string that \
         contains numbers and lower case letters. This value is generated at the time that a new \
         identity store is created.\n"]
  user_id : resource_id; [@ocaml.doc "The identifier for a user in the identity store.\n"]
  extensions : extension_names option;
      [@ocaml.doc
        "A collection of extension names indicating what extensions the service should retrieve \
         alongside other user attributes. [aws:identitystore:enterprise] is the only supported \
         extension name.\n"]
}
[@@ocaml.doc ""]

type nonrec filter = {
  attribute_path : attribute_path;
      [@ocaml.doc
        "The attribute path that is used to specify which attribute name to search. Length limit \
         is 255 characters. For example, [UserName] is a valid attribute path for the [ ListUsers] \
         API, and [DisplayName] is a valid attribute path for the [ ListGroups] API.\n"]
  attribute_value : sensitive_string_type;
      [@ocaml.doc
        "Represents the data for an attribute. Each attribute value is described as a name-value \
         pair. \n"]
}
[@@ocaml.doc
  "A query filter used by [ListUsers] and [ListGroups]. This filter object provides the attribute \
   name and attribute value to search users or groups.\n"]

type nonrec filters = filter list [@@ocaml.doc ""]

type nonrec group = {
  group_id : resource_id; [@ocaml.doc "The identifier for a group in the identity store.\n"]
  display_name : group_display_name option;
      [@ocaml.doc
        "The display name value for the group. The length limit is 1,024 characters. This value \
         can consist of letters, accented characters, symbols, numbers, punctuation, tab, new \
         line, carriage return, space, and nonbreaking space in this attribute. This value is \
         specified at the time the group is created and stored as an attribute of the group object \
         in the identity store.\n\n\
        \ Prefix search supports a maximum of 1,000 characters for the string.\n\
        \ "]
  external_ids : external_ids option;
      [@ocaml.doc
        "A list of [ExternalId] objects that contains the identifiers issued to this resource by \
         an external identity provider.\n"]
  description : sensitive_string_type option;
      [@ocaml.doc "A string containing a description of the specified group.\n"]
  created_at : date_type option; [@ocaml.doc "The date and time the group was created.\n"]
  updated_at : date_type option; [@ocaml.doc "The date and time the group was last updated.\n"]
  created_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that created the group.\n"]
  updated_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that last updated the group.\n"]
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
}
[@@ocaml.doc "A group object that contains the metadata and attributes for a specified group.\n"]

type nonrec group_membership_resource = Smaws_Lib.CoreTypes.Resource.t [@@ocaml.doc ""]

type nonrec group_resource = Smaws_Lib.CoreTypes.Resource.t [@@ocaml.doc ""]

type nonrec groups = group list [@@ocaml.doc ""]

type nonrec retry_after_seconds = int [@@ocaml.doc ""]

type nonrec internal_server_exception = {
  message : exception_message option; [@ocaml.doc ""]
  request_id : request_id option;
      [@ocaml.doc
        "The identifier for each request. This value is a globally unique ID that is generated by \
         the identity store service for each sent request, and is then returned inside the \
         exception if the request fails.\n"]
  retry_after_seconds : retry_after_seconds option;
      [@ocaml.doc "The number of seconds to wait before retrying the next request.\n"]
}
[@@ocaml.doc
  "The request processing has failed because of an unknown error, exception or failure with an \
   internal server.\n"]

type nonrec list_group_memberships_response = {
  group_memberships : group_memberships;
      [@ocaml.doc "A list of [GroupMembership] objects in the group.\n"]
  next_token : next_token option;
      [@ocaml.doc
        "The pagination token used for the [ListUsers], [ListGroups], and [ ListGroupMemberships] \
         API operations. This value is generated by the identity store service. It is returned in \
         the API response if the total results are more than the size of one page. This token is \
         also returned when it is used in the API request to search for the next page.\n"]
}
[@@ocaml.doc ""]

type nonrec list_group_memberships_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  group_id : resource_id; [@ocaml.doc "The identifier for a group in the identity store.\n"]
  max_results : max_results option;
      [@ocaml.doc
        "The maximum number of results to be returned per request. This parameter is used in all [ \
         List] requests to specify how many results to return in one page.\n"]
  next_token : next_token option;
      [@ocaml.doc
        "The pagination token used for the [ListUsers], [ListGroups] and [ ListGroupMemberships] \
         API operations. This value is generated by the identity store service. It is returned in \
         the API response if the total results are more than the size of one page. This token is \
         also returned when it is used in the API request to search for the next page.\n"]
}
[@@ocaml.doc ""]

type nonrec list_groups_response = {
  groups : groups; [@ocaml.doc "A list of [Group] objects in the identity store.\n"]
  next_token : next_token option;
      [@ocaml.doc
        "The pagination token used for the [ListUsers] and [ListGroups] API operations. This value \
         is generated by the identity store service. It is returned in the API response if the \
         total results are more than the size of one page. This token is also returned when it is \
         used in the API request to search for the next page.\n"]
}
[@@ocaml.doc ""]

type nonrec list_groups_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc
        "The globally unique identifier for the identity store, such as [d-1234567890]. In this \
         example, [d-] is a fixed prefix, and [1234567890] is a randomly generated string that \
         contains numbers and lower case letters. This value is generated at the time that a new \
         identity store is created.\n"]
  max_results : max_results option;
      [@ocaml.doc
        "The maximum number of results to be returned per request. This parameter is used in the [ \
         ListUsers] and [ListGroups] requests to specify how many results to return in one page. \
         The length limit is 50 characters.\n"]
  next_token : next_token option;
      [@ocaml.doc
        "The pagination token used for the [ListUsers] and [ListGroups] API operations. This value \
         is generated by the identity store service. It is returned in the API response if the \
         total results are more than the size of one page. This token is also returned when it is \
         used in the API request to search for the next page.\n"]
  filters : filters option;
      [@ocaml.doc
        "A list of [Filter] objects, which is used in the [ListUsers] and [ ListGroups] requests.\n"]
}
[@@ocaml.doc ""]

type nonrec user = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  user_id : resource_id; [@ocaml.doc "The identifier for a user in the identity store.\n"]
  user_name : user_name option;
      [@ocaml.doc
        "A unique string used to identify the user. The length limit is 128 characters. This value \
         can consist of letters, accented characters, symbols, numbers, and punctuation. This \
         value is specified at the time the user is created and stored as an attribute of the user \
         object in the identity store.\n"]
  external_ids : external_ids option;
      [@ocaml.doc
        "A list of [ExternalId] objects that contains the identifiers issued to this resource by \
         an external identity provider.\n"]
  name : name option; [@ocaml.doc "An object containing the name of the user.\n"]
  display_name : sensitive_string_type option;
      [@ocaml.doc
        "A string containing the name of the user that is formatted for display when the user is \
         referenced. For example, \"John Doe.\"\n\n\
        \ Prefix search supports a maximum of 1,000 characters for the string.\n\
        \ "]
  nick_name : sensitive_string_type option;
      [@ocaml.doc "A string containing an alternate name for the user.\n"]
  profile_url : sensitive_string_type option;
      [@ocaml.doc "A string containing a URL that might be associated with the user.\n"]
  emails : emails option;
      [@ocaml.doc
        "A list of [Email] objects containing email addresses associated with the user.\n"]
  addresses : addresses option;
      [@ocaml.doc "A list of [Address] objects containing addresses associated with the user.\n"]
  phone_numbers : phone_numbers option;
      [@ocaml.doc
        "A list of [PhoneNumber] objects containing phone numbers associated with the user.\n"]
  user_type : sensitive_string_type option;
      [@ocaml.doc
        "A string indicating the type of user. Possible values are left unspecified. The value can \
         vary based on your specific use case.\n"]
  title : sensitive_string_type option;
      [@ocaml.doc
        "A string containing the title of the user. Possible values are left unspecified. The \
         value can vary based on your specific use case.\n"]
  preferred_language : sensitive_string_type option;
      [@ocaml.doc
        "A string containing the preferred language of the user. For example, \"American English\" \
         or \"en-us.\"\n"]
  locale : sensitive_string_type option;
      [@ocaml.doc "A string containing the geographical region or location of the user.\n"]
  timezone : sensitive_string_type option;
      [@ocaml.doc "A string containing the time zone of the user.\n"]
  user_status : user_status option; [@ocaml.doc "The current status of the user account.\n"]
  photos : photos option;
      [@ocaml.doc
        "A list of photos associated with the user. Users can have up to 3 photos with metadata \
         including type, display name, and primary designation.\n"]
  website : sensitive_string_type option;
      [@ocaml.doc
        "The user's personal website or blog URL. This field stores website information for \
         personal or professional use.\n"]
  birthdate : sensitive_string_type option;
      [@ocaml.doc
        "The user's birthdate in YYYY-MM-DD format. This field stores personal birthdate \
         information for the user.\n"]
  roles : roles option;
      [@ocaml.doc "A list of [Role] objects containing roles associated with the user.\n"]
  created_at : date_type option; [@ocaml.doc "The date and time the user was created.\n"]
  created_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that created the user.\n"]
  updated_at : date_type option; [@ocaml.doc "The date and time the user was last updated.\n"]
  updated_by : string_type option;
      [@ocaml.doc "The identifier of the user or system that last updated the user.\n"]
  extensions : extensions option;
      [@ocaml.doc
        "A map of explicitly requested attribute extensions associated with the user. Not \
         populated if the user has no requested extensions.\n"]
}
[@@ocaml.doc "A user object that contains the metadata and attributes for a specified user.\n"]

type nonrec users = user list [@@ocaml.doc ""]

type nonrec list_users_response = {
  users : users; [@ocaml.doc "A list of [User] objects in the identity store.\n"]
  next_token : next_token option;
      [@ocaml.doc
        "The pagination token used for the [ListUsers] and [ListGroups] API operations. This value \
         is generated by the identity store service. It is returned in the API response if the \
         total results are more than the size of one page. This token is also returned when it is \
         used in the API request to search for the next page.\n"]
}
[@@ocaml.doc ""]

type nonrec list_users_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc
        "The globally unique identifier for the identity store, such as [d-1234567890]. In this \
         example, [d-] is a fixed prefix, and [1234567890] is a randomly generated string that \
         contains numbers and lower case letters. This value is generated at the time that a new \
         identity store is created.\n"]
  extensions : extension_names option;
      [@ocaml.doc
        "A collection of extension names indicating what extensions the service should retrieve \
         alongside other user attributes. [aws:identitystore:enterprise] is the only supported \
         extension name.\n"]
  max_results : max_results option;
      [@ocaml.doc
        "The maximum number of results to be returned per request. This parameter is used in the [ \
         ListUsers] and [ListGroups] requests to specify how many results to return in one page. \
         The length limit is 50 characters.\n"]
  next_token : next_token option;
      [@ocaml.doc
        "The pagination token used for the [ListUsers] and [ListGroups] API operations. This value \
         is generated by the identity store service. It is returned in the API response if the \
         total results are more than the size of one page. This token is also returned when it is \
         used in the API request to search for the next page.\n"]
  filters : filters option;
      [@ocaml.doc
        "A list of [Filter] objects, which is used in the [ListUsers] and [ ListGroups] requests. \n"]
}
[@@ocaml.doc ""]

type nonrec throttling_exception_reason = KMS_THROTTLING [@ocaml.doc ""] [@@ocaml.doc ""]

type nonrec throttling_exception = {
  message : exception_message option; [@ocaml.doc ""]
  request_id : request_id option;
      [@ocaml.doc
        "The identifier for each request. This value is a globally unique ID that is generated by \
         the identity store service for each sent request, and is then returned inside the \
         exception if the request fails.\n"]
  retry_after_seconds : retry_after_seconds option;
      [@ocaml.doc "The number of seconds to wait before retrying the next request.\n"]
  reason : throttling_exception_reason option;
      [@ocaml.doc
        "Indicates the reason for the throttling error when the service is unable to access a \
         Customer Managed KMS key. For non-KMS permission errors, this field is not included.\n"]
}
[@@ocaml.doc
  "Indicates that the principal has crossed the throttling limits of the API operations.\n"]

type nonrec update_group_response = unit [@@ocaml.doc ""]

type nonrec update_group_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  group_id : resource_id; [@ocaml.doc "The identifier for a group in the identity store.\n"]
  operations : attribute_operations;
      [@ocaml.doc
        "A list of [AttributeOperation] objects to apply to the requested group. These operations \
         might add, replace, or remove an attribute. For more information on the attributes that \
         can be added, replaced, or removed, see \
         {{:https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_Group.html}Group}.\n"]
}
[@@ocaml.doc ""]

type nonrec update_user_response = unit [@@ocaml.doc ""]

type nonrec update_user_request = {
  identity_store_id : identity_store_id;
      [@ocaml.doc "The globally unique identifier for the identity store.\n"]
  user_id : resource_id; [@ocaml.doc "The identifier for a user in the identity store.\n"]
  operations : attribute_operations;
      [@ocaml.doc
        "A list of [AttributeOperation] objects to apply to the requested user. These operations \
         might add, replace, or remove an attribute. For more information on the attributes that \
         can be added, replaced, or removed, see \
         {{:https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_User.html}User}.\n"]
}
[@@ocaml.doc ""]

type nonrec user_resource = Smaws_Lib.CoreTypes.Resource.t [@@ocaml.doc ""]
