type nonrec string_ = string [@@ocaml.doc ""]

type nonrec active_sessions_exceeded_exception = { message : string_ option [@ocaml.doc ""] }
[@@ocaml.doc
  "The Amazon Redshift Data API operation failed because the maximum number of active sessions \
   exceeded.\n"]

type nonrec active_statements_exceeded_exception = { message : string_ option [@ocaml.doc ""] }
[@@ocaml.doc "The number of active statements exceeds the limit.\n"]

type nonrec validation_exception = {
  message : string_ option; [@ocaml.doc "The exception message.\n"]
}
[@@ocaml.doc "The Amazon Redshift Data API operation failed due to invalid input. \n"]

type nonrec resource_not_found_exception = {
  message : string_; [@ocaml.doc "The exception message.\n"]
  resource_id : string_; [@ocaml.doc "Resource identifier associated with the exception.\n"]
}
[@@ocaml.doc "The Amazon Redshift Data API operation failed due to a missing resource. \n"]

type nonrec internal_server_exception = {
  message : string_; [@ocaml.doc "The exception message.\n"]
}
[@@ocaml.doc "The Amazon Redshift Data API operation failed due to invalid input. \n"]

type nonrec batch_execute_statement_exception = {
  message : string_; [@ocaml.doc ""]
  statement_id : string_; [@ocaml.doc "Statement identifier of the exception.\n"]
}
[@@ocaml.doc "An SQL statement encountered an environmental error while running.\n"]

type nonrec uui_d = string [@@ocaml.doc ""]

type nonrec workgroup_name_string = string [@@ocaml.doc ""]

type nonrec secret_arn = string [@@ocaml.doc ""]

type nonrec db_group_list = string_ list [@@ocaml.doc ""]

type nonrec cluster_identifier_string = string [@@ocaml.doc ""]

type nonrec batch_execute_statement_output = {
  id : uui_d option;
      [@ocaml.doc
        "The identifier of the SQL statement whose results are to be fetched. This value is a \
         universally unique identifier (UUID) generated by Amazon Redshift Data API. This \
         identifier is returned by [BatchExecuteStatment]. \n"]
  created_at : Smaws_Lib.Smithy_api.Types.timestamp option;
      [@ocaml.doc "The date and time (UTC) the statement was created. \n"]
  cluster_identifier : cluster_identifier_string option;
      [@ocaml.doc
        "The cluster identifier. This element is not returned when connecting to a serverless \
         workgroup. \n"]
  db_user : string_ option; [@ocaml.doc "The database user name.\n"]
  db_groups : db_group_list option;
      [@ocaml.doc "A list of colon (:) separated names of database groups.\n"]
  database : string_ option; [@ocaml.doc "The name of the database.\n"]
  secret_arn : secret_arn option;
      [@ocaml.doc "The name or ARN of the secret that enables access to the database. \n"]
  workgroup_name : workgroup_name_string option;
      [@ocaml.doc
        "The serverless workgroup name or Amazon Resource Name (ARN). This element is not returned \
         when connecting to a provisioned cluster.\n"]
  session_id : uui_d option; [@ocaml.doc "The session identifier of the query.\n"]
}
[@@ocaml.doc ""]

type nonrec session_alive_seconds = int [@@ocaml.doc ""]

type nonrec result_format_string = JSON [@ocaml.doc ""] | CSV [@ocaml.doc ""] [@@ocaml.doc ""]

type nonrec client_token = string [@@ocaml.doc ""]

type nonrec parameter_value = string [@@ocaml.doc ""]

type nonrec parameter_name = string [@@ocaml.doc ""]

type nonrec sql_parameter = {
  name : parameter_name; [@ocaml.doc "The name of the parameter.\n"]
  value : parameter_value;
      [@ocaml.doc
        "The value of the parameter. Amazon Redshift implicitly converts to the proper data type. \
         For more information, see \
         {{:https://docs.aws.amazon.com/redshift/latest/dg/c_Supported_data_types.html}Data types} \
         in the {i Amazon Redshift Database Developer Guide}. \n"]
}
[@@ocaml.doc "A parameter used in a SQL statement.\n"]

type nonrec sql_parameters_list = sql_parameter list [@@ocaml.doc ""]

type nonrec statement_name_string = string [@@ocaml.doc ""]

type nonrec statement_string = string [@@ocaml.doc ""]

type nonrec sql_list = statement_string list [@@ocaml.doc ""]

type nonrec batch_execute_statement_input = {
  sqls : sql_list;
      [@ocaml.doc
        "One or more SQL statements to run. The SQL statements are run as a single transaction. \
         They run serially in the order of the array. Subsequent SQL statements don't start until \
         the previous statement in the array completes. If any SQL statement fails, then because \
         they are run as one transaction, all work is rolled back.\n"]
  cluster_identifier : cluster_identifier_string option;
      [@ocaml.doc
        "The cluster identifier. This parameter is required when connecting to a cluster and \
         authenticating using either Secrets Manager or temporary credentials. \n"]
  secret_arn : secret_arn option;
      [@ocaml.doc
        "The name or ARN of the secret that enables access to the database. This parameter is \
         required when authenticating using Secrets Manager. \n"]
  db_user : string_ option;
      [@ocaml.doc
        "The database user name. This parameter is required when connecting to a cluster as a \
         database user and authenticating using temporary credentials. \n"]
  database : string_ option;
      [@ocaml.doc
        "The name of the database. This parameter is required when authenticating using either \
         Secrets Manager or temporary credentials. \n"]
  with_event : Smaws_Lib.Smithy_api.Types.boolean_ option;
      [@ocaml.doc
        "A value that indicates whether to send an event to the Amazon EventBridge event bus after \
         the SQL statements run. \n"]
  statement_name : statement_name_string option;
      [@ocaml.doc
        "The name of the SQL statements. You can name the SQL statements when you create them to \
         identify the query. \n"]
  parameters : sql_parameters_list option;
      [@ocaml.doc
        "The parameters for the SQL statements. The parameters are shared across all SQL \
         statements in the batch.\n"]
  workgroup_name : workgroup_name_string option;
      [@ocaml.doc
        "The serverless workgroup name or Amazon Resource Name (ARN). This parameter is required \
         when connecting to a serverless workgroup and authenticating using either Secrets Manager \
         or temporary credentials.\n"]
  client_token : client_token option;
      [@ocaml.doc
        "A unique, case-sensitive identifier that you provide to ensure the idempotency of the \
         request.\n"]
  result_format : result_format_string option;
      [@ocaml.doc
        "The data format of the result of the SQL statement. If no format is specified, the \
         default is JSON.\n"]
  session_keep_alive_seconds : session_alive_seconds option;
      [@ocaml.doc
        "The number of seconds to keep the session alive after the query finishes. The maximum \
         time a session can keep alive is 24 hours. After 24 hours, the session is forced closed \
         and the query is terminated.\n"]
  session_id : uui_d option; [@ocaml.doc "The session identifier of the query.\n"]
}
[@@ocaml.doc ""]

type nonrec blob = bytes [@@ocaml.doc ""]

type nonrec boxed_boolean = bool [@@ocaml.doc ""]

type nonrec boxed_double = float [@@ocaml.doc ""]

type nonrec boxed_long = Smaws_Lib.CoreTypes.Int64.t [@@ocaml.doc ""]

type nonrec query_timeout_exception = { message : string_ option [@ocaml.doc ""] }
[@@ocaml.doc "The Amazon Redshift Data API operation failed due to timeout.\n"]

type nonrec database_connection_exception = { message : string_ [@ocaml.doc ""] }
[@@ocaml.doc "Connection to a database failed.\n"]

type nonrec cancel_statement_response = {
  status : Smaws_Lib.Smithy_api.Types.boolean_ option;
      [@ocaml.doc "A value that indicates whether the cancel statement succeeded (true). \n"]
}
[@@ocaml.doc ""]

type nonrec cancel_statement_request = {
  id : uui_d;
      [@ocaml.doc
        "The identifier of the SQL statement to cancel. This value is a universally unique \
         identifier (UUID) generated by Amazon Redshift Data API. This identifier is returned by \
         [BatchExecuteStatment], [ExecuteStatment], and [ListStatements]. \n"]
}
[@@ocaml.doc ""]

type nonrec integer = int [@@ocaml.doc ""]

type nonrec bool_ = bool [@@ocaml.doc ""]

type nonrec column_metadata = {
  is_case_sensitive : bool_ option;
      [@ocaml.doc "A value that indicates whether the column is case-sensitive. \n"]
  is_currency : bool_ option;
      [@ocaml.doc "A value that indicates whether the column contains currency values.\n"]
  is_signed : bool_ option;
      [@ocaml.doc "A value that indicates whether an integer column is signed.\n"]
  label : string_ option; [@ocaml.doc "The label for the column. \n"]
  name : string_ option; [@ocaml.doc "The name of the column. \n"]
  nullable : integer option;
      [@ocaml.doc "A value that indicates whether the column is nullable. \n"]
  precision : integer option;
      [@ocaml.doc
        "The precision value of a decimal number column, or the column length for a non-numeric \
         column. \n"]
  scale : integer option; [@ocaml.doc "The scale value of a decimal number column. \n"]
  schema_name : string_ option;
      [@ocaml.doc "The name of the schema that contains the table that includes the column.\n"]
  table_name : string_ option; [@ocaml.doc "The name of the table that includes the column. \n"]
  type_name : string_ option; [@ocaml.doc "The database-specific data type of the column. \n"]
  length : integer option; [@ocaml.doc "The length of the column.\n"]
  column_default : string_ option; [@ocaml.doc "The default value of the column. \n"]
}
[@@ocaml.doc "The properties (metadata) of a column. \n"]

type nonrec column_list = column_metadata list [@@ocaml.doc ""]

type nonrec column_metadata_list = column_metadata list [@@ocaml.doc ""]

type nonrec database_list = string_ list [@@ocaml.doc ""]

type nonrec long = Smaws_Lib.CoreTypes.Int64.t [@@ocaml.doc ""]

type nonrec statement_status_string =
  | SUBMITTED [@ocaml.doc ""]
  | PICKED [@ocaml.doc ""]
  | STARTED [@ocaml.doc ""]
  | FINISHED [@ocaml.doc ""]
  | ABORTED [@ocaml.doc ""]
  | FAILED [@ocaml.doc ""]
[@@ocaml.doc ""]

type nonrec sub_statement_data = {
  id : uui_d;
      [@ocaml.doc
        "The identifier of the SQL statement. This value is a universally unique identifier (UUID) \
         generated by Amazon Redshift Data API. A suffix indicates the number of the SQL \
         statement. For example, [d9b6c0c9-0747-4bf4-b142-e8883122f766:2] has a suffix of [:2] \
         that indicates the second SQL statement of a batch query.\n"]
  duration : long option; [@ocaml.doc "The amount of time in nanoseconds that the statement ran.\n"]
  error : string_ option;
      [@ocaml.doc
        "The error message from the cluster if the SQL statement encountered an error while running.\n"]
  status : statement_status_string option;
      [@ocaml.doc
        "The status of the SQL statement. An example is the that the SQL statement finished. \n"]
  created_at : Smaws_Lib.Smithy_api.Types.timestamp option;
      [@ocaml.doc "The date and time (UTC) the statement was created. \n"]
  updated_at : Smaws_Lib.Smithy_api.Types.timestamp option;
      [@ocaml.doc "The date and time (UTC) that the statement metadata was last updated.\n"]
  query_string : statement_string option; [@ocaml.doc "The SQL statement text.\n"]
  result_rows : long option;
      [@ocaml.doc
        "Either the number of rows returned from the SQL statement or the number of rows affected. \
         If result size is greater than zero, the result rows can be the number of rows affected \
         by SQL statements such as INSERT, UPDATE, DELETE, COPY, and others. A [-1] indicates the \
         value is null.\n"]
  result_size : long option;
      [@ocaml.doc
        "The size in bytes of the returned results. A [-1] indicates the value is null.\n"]
  redshift_query_id : long option;
      [@ocaml.doc
        "The SQL statement identifier. This value is a universally unique identifier (UUID) \
         generated by Amazon Redshift Data API. \n"]
  has_result_set : Smaws_Lib.Smithy_api.Types.boolean_ option;
      [@ocaml.doc
        "A value that indicates whether the statement has a result set. The result set can be \
         empty. The value is true for an empty result set.\n"]
}
[@@ocaml.doc "Information about an SQL statement.\n"]

type nonrec sub_statement_list = sub_statement_data list [@@ocaml.doc ""]

type nonrec status_string =
  | SUBMITTED [@ocaml.doc ""]
  | PICKED [@ocaml.doc ""]
  | STARTED [@ocaml.doc ""]
  | FINISHED [@ocaml.doc ""]
  | ABORTED [@ocaml.doc ""]
  | FAILED [@ocaml.doc ""]
  | ALL [@ocaml.doc ""]
[@@ocaml.doc ""]

type nonrec describe_statement_response = {
  id : uui_d;
      [@ocaml.doc
        "The identifier of the SQL statement described. This value is a universally unique \
         identifier (UUID) generated by Amazon Redshift Data API. \n"]
  secret_arn : secret_arn option;
      [@ocaml.doc
        "The name or Amazon Resource Name (ARN) of the secret that enables access to the database. \n"]
  db_user : string_ option; [@ocaml.doc "The database user name. \n"]
  database : string_ option; [@ocaml.doc "The name of the database. \n"]
  cluster_identifier : string_ option; [@ocaml.doc "The cluster identifier. \n"]
  duration : long option;
      [@ocaml.doc "The amount of time in nanoseconds that the statement ran. \n"]
  error : string_ option;
      [@ocaml.doc
        "The error message from the cluster if the SQL statement encountered an error while \
         running. \n"]
  status : status_string option;
      [@ocaml.doc
        "The status of the SQL statement being described. Status values are defined as follows: \n\n\
        \ {ul\n\
        \       {-  ABORTED - The query run was stopped by the user. \n\
        \           \n\
        \            }\n\
        \       {-  ALL - A status value that includes all query statuses. This value can be used \
         to filter results. \n\
        \           \n\
        \            }\n\
        \       {-  FAILED - The query run failed. \n\
        \           \n\
        \            }\n\
        \       {-  FINISHED - The query has finished running. \n\
        \           \n\
        \            }\n\
        \       {-  PICKED - The query has been chosen to be run. \n\
        \           \n\
        \            }\n\
        \       {-  STARTED - The query run has started. \n\
        \           \n\
        \            }\n\
        \       {-  SUBMITTED - The query was submitted, but not yet processed. \n\
        \           \n\
        \            }\n\
        \       }\n\
        \  "]
  created_at : Smaws_Lib.Smithy_api.Types.timestamp option;
      [@ocaml.doc "The date and time (UTC) when the SQL statement was submitted to run. \n"]
  updated_at : Smaws_Lib.Smithy_api.Types.timestamp option;
      [@ocaml.doc
        "The date and time (UTC) that the metadata for the SQL statement was last updated. An \
         example is the time the status last changed. \n"]
  redshift_pid : long option; [@ocaml.doc "The process identifier from Amazon Redshift. \n"]
  has_result_set : Smaws_Lib.Smithy_api.Types.boolean_ option;
      [@ocaml.doc
        "A value that indicates whether the statement has a result set. The result set can be \
         empty. The value is true for an empty result set. The value is true if any substatement \
         returns a result set.\n"]
  query_string : statement_string option; [@ocaml.doc "The SQL statement text. \n"]
  result_rows : long option;
      [@ocaml.doc
        "Either the number of rows returned from the SQL statement or the number of rows affected. \
         If result size is greater than zero, the result rows can be the number of rows affected \
         by SQL statements such as INSERT, UPDATE, DELETE, COPY, and others. A [-1] indicates the \
         value is null.\n"]
  result_size : long option;
      [@ocaml.doc
        "The size in bytes of the returned results. A [-1] indicates the value is null.\n"]
  redshift_query_id : long option;
      [@ocaml.doc
        "The identifier of the query generated by Amazon Redshift. These identifiers are also \
         available in the [query] column of the [STL_QUERY] system view. \n"]
  query_parameters : sql_parameters_list option;
      [@ocaml.doc "The parameters for the SQL statement.\n"]
  sub_statements : sub_statement_list option;
      [@ocaml.doc "The SQL statements from a multiple statement run.\n"]
  workgroup_name : workgroup_name_string option;
      [@ocaml.doc "The serverless workgroup name or Amazon Resource Name (ARN).\n"]
  result_format : result_format_string option;
      [@ocaml.doc "The data format of the result of the SQL statement.\n"]
  session_id : string_ option; [@ocaml.doc "The session identifier of the query.\n"]
}
[@@ocaml.doc ""]

type nonrec describe_statement_request = {
  id : uui_d;
      [@ocaml.doc
        "The identifier of the SQL statement to describe. This value is a universally unique \
         identifier (UUID) generated by Amazon Redshift Data API. A suffix indicates the number of \
         the SQL statement. For example, [d9b6c0c9-0747-4bf4-b142-e8883122f766:2] has a suffix of \
         [:2] that indicates the second SQL statement of a batch query. This identifier is \
         returned by [BatchExecuteStatment], [ExecuteStatement], and [ListStatements]. \n"]
}
[@@ocaml.doc ""]

type nonrec describe_table_response = {
  table_name : string_ option; [@ocaml.doc "The table name. \n"]
  column_list : column_list option; [@ocaml.doc "A list of columns in the table. \n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
}
[@@ocaml.doc ""]

type nonrec page_size = int [@@ocaml.doc ""]

type nonrec describe_table_request = {
  cluster_identifier : cluster_identifier_string option;
      [@ocaml.doc
        "The cluster identifier. This parameter is required when connecting to a cluster and \
         authenticating using either Secrets Manager or temporary credentials. \n"]
  secret_arn : secret_arn option;
      [@ocaml.doc
        "The name or ARN of the secret that enables access to the database. This parameter is \
         required when authenticating using Secrets Manager. \n"]
  db_user : string_ option;
      [@ocaml.doc
        "The database user name. This parameter is required when connecting to a cluster as a \
         database user and authenticating using temporary credentials. \n"]
  database : string_;
      [@ocaml.doc
        "The name of the database that contains the tables to be described. If [ConnectedDatabase] \
         is not specified, this is also the database to connect to with your authentication \
         credentials.\n"]
  connected_database : string_ option;
      [@ocaml.doc
        "A database name. The connected database is specified when you connect with your \
         authentication credentials. \n"]
  schema : string_ option;
      [@ocaml.doc
        "The schema that contains the table. If no schema is specified, then matching tables for \
         all schemas are returned. \n"]
  table : string_ option;
      [@ocaml.doc
        "The table name. If no table is specified, then all tables for all matching schemas are \
         returned. If no table and no schema is specified, then all tables for all schemas in the \
         database are returned\n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
  max_results : page_size option;
      [@ocaml.doc
        "The maximum number of tables to return in the response. If more tables exist than fit in \
         one response, then [NextToken] is returned to page through the results. \n"]
  workgroup_name : workgroup_name_string option;
      [@ocaml.doc
        "The serverless workgroup name or Amazon Resource Name (ARN). This parameter is required \
         when connecting to a serverless workgroup and authenticating using either Secrets Manager \
         or temporary credentials.\n"]
}
[@@ocaml.doc ""]

type nonrec execute_statement_exception = {
  message : string_; [@ocaml.doc "The exception message.\n"]
  statement_id : string_; [@ocaml.doc "Statement identifier of the exception.\n"]
}
[@@ocaml.doc "The SQL statement encountered an environmental error while running.\n"]

type nonrec execute_statement_output = {
  id : uui_d option;
      [@ocaml.doc
        "The identifier of the SQL statement whose results are to be fetched. This value is a \
         universally unique identifier (UUID) generated by Amazon Redshift Data API. \n"]
  created_at : Smaws_Lib.Smithy_api.Types.timestamp option;
      [@ocaml.doc "The date and time (UTC) the statement was created. \n"]
  cluster_identifier : cluster_identifier_string option;
      [@ocaml.doc
        "The cluster identifier. This element is not returned when connecting to a serverless \
         workgroup. \n"]
  db_user : string_ option; [@ocaml.doc "The database user name.\n"]
  db_groups : db_group_list option;
      [@ocaml.doc "A list of colon (:) separated names of database groups.\n"]
  database : string_ option; [@ocaml.doc "The name of the database.\n"]
  secret_arn : secret_arn option;
      [@ocaml.doc "The name or ARN of the secret that enables access to the database. \n"]
  workgroup_name : workgroup_name_string option;
      [@ocaml.doc
        "The serverless workgroup name or Amazon Resource Name (ARN). This element is not returned \
         when connecting to a provisioned cluster.\n"]
  session_id : uui_d option; [@ocaml.doc "The session identifier of the query.\n"]
}
[@@ocaml.doc ""]

type nonrec execute_statement_input = {
  sql : statement_string; [@ocaml.doc "The SQL statement text to run. \n"]
  cluster_identifier : cluster_identifier_string option;
      [@ocaml.doc
        "The cluster identifier. This parameter is required when connecting to a cluster and \
         authenticating using either Secrets Manager or temporary credentials. \n"]
  secret_arn : secret_arn option;
      [@ocaml.doc
        "The name or ARN of the secret that enables access to the database. This parameter is \
         required when authenticating using Secrets Manager. \n"]
  db_user : string_ option;
      [@ocaml.doc
        "The database user name. This parameter is required when connecting to a cluster as a \
         database user and authenticating using temporary credentials. \n"]
  database : string_ option;
      [@ocaml.doc
        "The name of the database. This parameter is required when authenticating using either \
         Secrets Manager or temporary credentials. \n"]
  with_event : Smaws_Lib.Smithy_api.Types.boolean_ option;
      [@ocaml.doc
        "A value that indicates whether to send an event to the Amazon EventBridge event bus after \
         the SQL statement runs. \n"]
  statement_name : statement_name_string option;
      [@ocaml.doc
        "The name of the SQL statement. You can name the SQL statement when you create it to \
         identify the query. \n"]
  parameters : sql_parameters_list option; [@ocaml.doc "The parameters for the SQL statement.\n"]
  workgroup_name : workgroup_name_string option;
      [@ocaml.doc
        "The serverless workgroup name or Amazon Resource Name (ARN). This parameter is required \
         when connecting to a serverless workgroup and authenticating using either Secrets Manager \
         or temporary credentials.\n"]
  client_token : client_token option;
      [@ocaml.doc
        "A unique, case-sensitive identifier that you provide to ensure the idempotency of the \
         request.\n"]
  result_format : result_format_string option;
      [@ocaml.doc
        "The data format of the result of the SQL statement. If no format is specified, the \
         default is JSON.\n"]
  session_keep_alive_seconds : session_alive_seconds option;
      [@ocaml.doc
        "The number of seconds to keep the session alive after the query finishes. The maximum \
         time a session can keep alive is 24 hours. After 24 hours, the session is forced closed \
         and the query is terminated.\n"]
  session_id : uui_d option; [@ocaml.doc "The session identifier of the query.\n"]
}
[@@ocaml.doc ""]

type nonrec field =
  | IsNull of boxed_boolean [@ocaml.doc "A value that indicates whether the data is NULL. \n"]
  | BooleanValue of boxed_boolean [@ocaml.doc "A value of the Boolean data type. \n"]
  | LongValue of boxed_long [@ocaml.doc "A value of the long data type. \n"]
  | DoubleValue of boxed_double [@ocaml.doc "A value of the double data type. \n"]
  | StringValue of string_ [@ocaml.doc "A value of the string data type. \n"]
  | BlobValue of blob [@ocaml.doc "A value of the BLOB data type. \n"]
[@@ocaml.doc "A data value in a column. \n"]

type nonrec field_list = field list [@@ocaml.doc ""]

type nonrec query_records =
  | CSVRecords of string_ [@ocaml.doc "The results of the SQL statement in CSV format.\n"]
[@@ocaml.doc "The results of the SQL statement.\n"]

type nonrec formatted_sql_records = query_records list [@@ocaml.doc ""]

type nonrec sql_records = field_list list [@@ocaml.doc ""]

type nonrec get_statement_result_response = {
  records : sql_records; [@ocaml.doc "The results of the SQL statement in JSON format.\n"]
  column_metadata : column_metadata_list option;
      [@ocaml.doc "The properties (metadata) of a column. \n"]
  total_num_rows : long option;
      [@ocaml.doc
        "The total number of rows in the result set returned from a query. You can use this number \
         to estimate the number of calls to the [GetStatementResult] operation needed to page \
         through the results. \n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
}
[@@ocaml.doc ""]

type nonrec get_statement_result_request = {
  id : uui_d;
      [@ocaml.doc
        "The identifier of the SQL statement whose results are to be fetched. This value is a \
         universally unique identifier (UUID) generated by Amazon Redshift Data API. A suffix \
         indicates then number of the SQL statement. For example, \
         [d9b6c0c9-0747-4bf4-b142-e8883122f766:2] has a suffix of [:2] that indicates the second \
         SQL statement of a batch query. This identifier is returned by [BatchExecuteStatment], \
         [ExecuteStatment], and [ListStatements]. \n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
}
[@@ocaml.doc ""]

type nonrec get_statement_result_v2_response = {
  records : formatted_sql_records; [@ocaml.doc "The results of the SQL statement in CSV format.\n"]
  column_metadata : column_metadata_list option;
      [@ocaml.doc "The properties (metadata) of a column.\n"]
  total_num_rows : long option;
      [@ocaml.doc
        "The total number of rows in the result set returned from a query. You can use this number \
         to estimate the number of calls to the [GetStatementResultV2] operation needed to page \
         through the results. \n"]
  result_format : result_format_string option;
      [@ocaml.doc "The data format of the result of the SQL statement.\n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
}
[@@ocaml.doc ""]

type nonrec get_statement_result_v2_request = {
  id : uui_d;
      [@ocaml.doc
        "The identifier of the SQL statement whose results are to be fetched. This value is a \
         universally unique identifier (UUID) generated by Amazon Redshift Data API. A suffix \
         indicates then number of the SQL statement. For example, \
         [d9b6c0c9-0747-4bf4-b142-e8883122f766:2] has a suffix of [:2] that indicates the second \
         SQL statement of a batch query. This identifier is returned by [BatchExecuteStatment], \
         [ExecuteStatment], and [ListStatements]. \n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request.\n"]
}
[@@ocaml.doc ""]

type nonrec list_databases_response = {
  databases : database_list option; [@ocaml.doc "The names of databases. \n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
}
[@@ocaml.doc ""]

type nonrec list_databases_request = {
  cluster_identifier : cluster_identifier_string option;
      [@ocaml.doc
        "The cluster identifier. This parameter is required when connecting to a cluster and \
         authenticating using either Secrets Manager or temporary credentials. \n"]
  database : string_;
      [@ocaml.doc
        "The name of the database. This parameter is required when authenticating using either \
         Secrets Manager or temporary credentials. \n"]
  secret_arn : secret_arn option;
      [@ocaml.doc
        "The name or ARN of the secret that enables access to the database. This parameter is \
         required when authenticating using Secrets Manager. \n"]
  db_user : string_ option;
      [@ocaml.doc
        "The database user name. This parameter is required when connecting to a cluster as a \
         database user and authenticating using temporary credentials. \n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
  max_results : page_size option;
      [@ocaml.doc
        "The maximum number of databases to return in the response. If more databases exist than \
         fit in one response, then [NextToken] is returned to page through the results. \n"]
  workgroup_name : workgroup_name_string option;
      [@ocaml.doc
        "The serverless workgroup name or Amazon Resource Name (ARN). This parameter is required \
         when connecting to a serverless workgroup and authenticating using either Secrets Manager \
         or temporary credentials.\n"]
}
[@@ocaml.doc ""]

type nonrec schema_list = string_ list [@@ocaml.doc ""]

type nonrec list_schemas_response = {
  schemas : schema_list option; [@ocaml.doc "The schemas that match the request pattern. \n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
}
[@@ocaml.doc ""]

type nonrec list_schemas_request = {
  cluster_identifier : cluster_identifier_string option;
      [@ocaml.doc
        "The cluster identifier. This parameter is required when connecting to a cluster and \
         authenticating using either Secrets Manager or temporary credentials. \n"]
  secret_arn : secret_arn option;
      [@ocaml.doc
        "The name or ARN of the secret that enables access to the database. This parameter is \
         required when authenticating using Secrets Manager. \n"]
  db_user : string_ option;
      [@ocaml.doc
        "The database user name. This parameter is required when connecting to a cluster as a \
         database user and authenticating using temporary credentials. \n"]
  database : string_;
      [@ocaml.doc
        "The name of the database that contains the schemas to list. If [ConnectedDatabase] is not \
         specified, this is also the database to connect to with your authentication credentials.\n"]
  connected_database : string_ option;
      [@ocaml.doc
        "A database name. The connected database is specified when you connect with your \
         authentication credentials. \n"]
  schema_pattern : string_ option;
      [@ocaml.doc
        "A pattern to filter results by schema name. Within a schema pattern, \"%\" means match \
         any substring of 0 or more characters and \"_\" means match any one character. Only \
         schema name entries matching the search pattern are returned. \n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
  max_results : page_size option;
      [@ocaml.doc
        "The maximum number of schemas to return in the response. If more schemas exist than fit \
         in one response, then [NextToken] is returned to page through the results. \n"]
  workgroup_name : workgroup_name_string option;
      [@ocaml.doc
        "The serverless workgroup name or Amazon Resource Name (ARN). This parameter is required \
         when connecting to a serverless workgroup and authenticating using either Secrets Manager \
         or temporary credentials.\n"]
}
[@@ocaml.doc ""]

type nonrec statement_string_list = statement_string list [@@ocaml.doc ""]

type nonrec statement_data = {
  id : uui_d;
      [@ocaml.doc
        "The SQL statement identifier. This value is a universally unique identifier (UUID) \
         generated by Amazon Redshift Data API. \n"]
  query_string : statement_string option; [@ocaml.doc "The SQL statement.\n"]
  query_strings : statement_string_list option;
      [@ocaml.doc
        "One or more SQL statements. Each query string in the array corresponds to one of the \
         queries in a batch query request.\n"]
  secret_arn : secret_arn option;
      [@ocaml.doc
        "The name or Amazon Resource Name (ARN) of the secret that enables access to the database. \n"]
  status : status_string option;
      [@ocaml.doc
        "The status of the SQL statement. An example is the that the SQL statement finished. \n"]
  statement_name : statement_name_string option; [@ocaml.doc "The name of the SQL statement. \n"]
  created_at : Smaws_Lib.Smithy_api.Types.timestamp option;
      [@ocaml.doc "The date and time (UTC) the statement was created. \n"]
  updated_at : Smaws_Lib.Smithy_api.Types.timestamp option;
      [@ocaml.doc "The date and time (UTC) that the statement metadata was last updated.\n"]
  query_parameters : sql_parameters_list option;
      [@ocaml.doc "The parameters used in a SQL statement.\n"]
  is_batch_statement : Smaws_Lib.Smithy_api.Types.boolean_ option;
      [@ocaml.doc "A value that indicates whether the statement is a batch query request.\n"]
  result_format : result_format_string option;
      [@ocaml.doc "The data format of the result of the SQL statement.\n"]
  session_id : uui_d option; [@ocaml.doc "The session identifier of the query.\n"]
}
[@@ocaml.doc "The SQL statement to run.\n"]

type nonrec statement_list = statement_data list [@@ocaml.doc ""]

type nonrec list_statements_response = {
  statements : statement_list; [@ocaml.doc "The SQL statements. \n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
}
[@@ocaml.doc ""]

type nonrec list_statements_limit = int [@@ocaml.doc ""]

type nonrec list_statements_request = {
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
  max_results : list_statements_limit option;
      [@ocaml.doc
        "The maximum number of SQL statements to return in the response. If more SQL statements \
         exist than fit in one response, then [NextToken] is returned to page through the results. \n"]
  statement_name : statement_name_string option;
      [@ocaml.doc
        "The name of the SQL statement specified as input to [BatchExecuteStatement] or \
         [ExecuteStatement] to identify the query. You can list multiple statements by providing a \
         prefix that matches the beginning of the statement name. For example, to list \
         myStatement1, myStatement2, myStatement3, and so on, then provide the a value of \
         [myStatement]. Data API does a case-sensitive match of SQL statement names to the prefix \
         value you provide. \n"]
  status : status_string option;
      [@ocaml.doc
        "The status of the SQL statement to list. Status values are defined as follows: \n\n\
        \ {ul\n\
        \       {-  ABORTED - The query run was stopped by the user. \n\
        \           \n\
        \            }\n\
        \       {-  ALL - A status value that includes all query statuses. This value can be used \
         to filter results. \n\
        \           \n\
        \            }\n\
        \       {-  FAILED - The query run failed. \n\
        \           \n\
        \            }\n\
        \       {-  FINISHED - The query has finished running. \n\
        \           \n\
        \            }\n\
        \       {-  PICKED - The query has been chosen to be run. \n\
        \           \n\
        \            }\n\
        \       {-  STARTED - The query run has started. \n\
        \           \n\
        \            }\n\
        \       {-  SUBMITTED - The query was submitted, but not yet processed. \n\
        \           \n\
        \            }\n\
        \       }\n\
        \  "]
  role_level : Smaws_Lib.Smithy_api.Types.boolean_ option;
      [@ocaml.doc
        "A value that filters which statements to return in the response. If true, all statements \
         run by the caller's IAM role are returned. If false, only statements run by the caller's \
         IAM role in the current IAM session are returned. The default is true. \n"]
  database : string_ option;
      [@ocaml.doc
        "The name of the database when listing statements run against a [ClusterIdentifier] or \
         [WorkgroupName]. \n"]
  cluster_identifier : cluster_identifier_string option;
      [@ocaml.doc
        "The cluster identifier. Only statements that ran on this cluster are returned. When \
         providing [ClusterIdentifier], then [WorkgroupName] can't be specified.\n"]
  workgroup_name : workgroup_name_string option;
      [@ocaml.doc
        "The serverless workgroup name or Amazon Resource Name (ARN). Only statements that ran on \
         this workgroup are returned. When providing [WorkgroupName], then [ClusterIdentifier] \
         can't be specified.\n"]
}
[@@ocaml.doc ""]

type nonrec table_member = {
  name : string_ option; [@ocaml.doc "The name of the table. \n"]
  type_ : string_ option;
      [@ocaml.doc
        "The type of the table. Possible values include TABLE, VIEW, SYSTEM TABLE, GLOBAL \
         TEMPORARY, LOCAL TEMPORARY, ALIAS, and SYNONYM. \n"]
  schema : string_ option; [@ocaml.doc "The schema containing the table. \n"]
}
[@@ocaml.doc "The properties of a table. \n"]

type nonrec table_list = table_member list [@@ocaml.doc ""]

type nonrec list_tables_response = {
  tables : table_list option; [@ocaml.doc "The tables that match the request pattern. \n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
}
[@@ocaml.doc ""]

type nonrec list_tables_request = {
  cluster_identifier : cluster_identifier_string option;
      [@ocaml.doc
        "The cluster identifier. This parameter is required when connecting to a cluster and \
         authenticating using either Secrets Manager or temporary credentials. \n"]
  secret_arn : secret_arn option;
      [@ocaml.doc
        "The name or ARN of the secret that enables access to the database. This parameter is \
         required when authenticating using Secrets Manager. \n"]
  db_user : string_ option;
      [@ocaml.doc
        "The database user name. This parameter is required when connecting to a cluster as a \
         database user and authenticating using temporary credentials. \n"]
  database : string_;
      [@ocaml.doc
        "The name of the database that contains the tables to list. If [ConnectedDatabase] is not \
         specified, this is also the database to connect to with your authentication credentials.\n"]
  connected_database : string_ option;
      [@ocaml.doc
        "A database name. The connected database is specified when you connect with your \
         authentication credentials. \n"]
  schema_pattern : string_ option;
      [@ocaml.doc
        "A pattern to filter results by schema name. Within a schema pattern, \"%\" means match \
         any substring of 0 or more characters and \"_\" means match any one character. Only \
         schema name entries matching the search pattern are returned. If [SchemaPattern] is not \
         specified, then all tables that match [TablePattern] are returned. If neither \
         [SchemaPattern] or [TablePattern] are specified, then all tables are returned. \n"]
  table_pattern : string_ option;
      [@ocaml.doc
        "A pattern to filter results by table name. Within a table pattern, \"%\" means match any \
         substring of 0 or more characters and \"_\" means match any one character. Only table \
         name entries matching the search pattern are returned. If [TablePattern] is not \
         specified, then all tables that match [SchemaPattern]are returned. If neither \
         [SchemaPattern] or [TablePattern] are specified, then all tables are returned. \n"]
  next_token : string_ option;
      [@ocaml.doc
        "A value that indicates the starting point for the next set of response records in a \
         subsequent request. If a value is returned in a response, you can retrieve the next set \
         of records by providing this returned NextToken value in the next NextToken parameter and \
         retrying the command. If the NextToken field is empty, all response records have been \
         retrieved for the request. \n"]
  max_results : page_size option;
      [@ocaml.doc
        "The maximum number of tables to return in the response. If more tables exist than fit in \
         one response, then [NextToken] is returned to page through the results. \n"]
  workgroup_name : workgroup_name_string option;
      [@ocaml.doc
        "The serverless workgroup name or Amazon Resource Name (ARN). This parameter is required \
         when connecting to a serverless workgroup and authenticating using either Secrets Manager \
         or temporary credentials.\n"]
}
[@@ocaml.doc ""]
